<<<<<<< HEAD
#server:
#  port: 9192
#
#spring:
#  datasource:
#    username: test
#    password: 12341234
#    url: jdbc:mysql://13.209.42.64/lakeSide_hotel_db?serverTimezone=UTC&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      format_sql: true
#  servlet:
#    multipart:
#    max-file-size: 5MB
#    max-request-size: 5MB
#    file-size-threshold: 2KB
#
#    security:
#      jwt:
#        secret-key: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
#        expire-length: 3600000
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
=======
server:
  port: 9192

spring:

  # application.yml
  # spring:
  #   security:
  #     user:
  #       name: admin
  #       password: adminpassword

  datasource:
    username: root
    password: 12341234
    url: jdbc:mysql://localhost:3306/lakeSide_hotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

servlet:
  multipart:
    max-file-size: 5MB
    max-request-size: 5MB
    file-size-threshold: 2KB



logging:
  level:
    org.springframework.security.web: DEBUG

>>>>>>> f2a4376f1d3c4315c72d88de4738086adcb61fa8
